name: Build & Test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '18.x'
            - run: npm install
            - run: npm run ci:lint
            - run: npm run ci:build-libs
            - run: npm run ci:test-libs
